### PR TITLE
Verivital benchmark for CNN Pooling networks for MNIST dataset

### PR DESCRIPTION
**Pull request by Neelanjana314**

### CODE REVIEW

**Comment by stanleybak** [comment]
is the `shortname` for the benchmark `verivital` (the folder name) or `mnist_Conv_pool` (the `instances.csv` name)? The folder name and instances.csv `shortname` should be the same.

**Comment by stanleybak** [comment]
The sum of the timeouts is 25500 seconds (7.08 hours). The max total timeout should be 6 hours. please adjust the timeouts or number of instances.

**Comment by stanleybak** [comment]
The `shortname_instances.csv` file lists properties like `prop_0_0.02.vnnlib`, but these are contained in subfolders like `specs/avgpool_specs/`. Please update the path in `instances.csv` to include the subfolders.

**Comment by Neelanjana314** [comment]
Sure, thanks for the feedback. I will be updating the modifications in an hour.

**Comment by Neelanjana314** [comment]
I have updated the necessary modifications. Please let me know if any more changes are needed.

**Pull request merged**
