### PR TITLE
add cifar10 resnet benchmark

### PR DESCRIPTION
**Pull request by tcwangshiqi-columbia**
Please kindly find detailed benchmark descriptions including resnet models information and commands for generating random properties in Readme.

### CODE REVIEW

**Comment by huanzhang12** [comment]
@stanleybak Note that we enlarged the ResNet-4B model to make it around 14K neurons, so we now have a relatively large model (which is also scored) in our benchmark suite (for addressing [the issue](https://github.com/stanleybak/vnncomp2021/issues/2#issuecomment-854493193) of lacking large models). To compensate the difficulty caused by the larger network, we reduce epsilon for the ResNet-4B model from 2/255 to 1/255. It actually becomes easier than the previous model (CROWN verified accuracy is higher). if you feel we should stick to the previous smaller model, we can switch it back as well.

BTW, I just found that some PGD attack accuracy numbers reported on the README are outdated. I will update them tonight so don't merge this right now. But all the models and specifications are ready for your review.

**Comment by huanzhang12** [comment]
@stanleybak I further cleaned up the code and also made the PGD based property generation script usable on CPUs (it was depending on a GPU). I have made necessary changes and the PR is ready for your final review.

**Comment by stanleybak** [comment]
please rename your `<shortname>_instances.csv` file to be `cifar10_resnet_instances.csv`

**Comment by huanzhang12** [comment]
> please rename your `<shortname>_instances.csv` file to be `cifar10_resnet_instances.csv`

Done.

**Comment by stanleybak** [comment]
you also want to do this in the generation script

**Comment by huanzhang12** [comment]
> you also want to do this in the generation script

Done, sorry for forgetting to change it in the generation script.

**Pull request merged**
